services:
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  backend-web:
    build: .
    container_name: backend-web
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000

    volumes:
      - ./core:/app
      - static_volume:/app/static
      - ./core/media:/app/media
    expose:
      - "8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=False
    depends_on:
      - redis
  worker-celery:
    build: .
    container_name: worker-celery
    command: celery -A core worker --loglevel=info
    volumes:
      - ./core:/app
    depends_on:
      - redis
      - backend-web
  
      
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./core/locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://backend-web:8000
  
  worker:
    image: locustio/locust
    volumes:
      - ./core/locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
  

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - ./core/media:/home/app/media
    depends_on:
      - backend-web
      - redis


volumes:
  static_volume:
  media_volume: